lint:
  files_exist:
  - conf/igenomes.config
  - conf/igenomes_ignored.config
  - conf/igenomes.config
  - assets/multiqc_config.yml
  - assets/email_template.html
  - assets/sendmail_template.txt
  - assets/email_template.txt
  - conf/igenomes.config
  - conf/igenomes_ignored.config
  - assets/multiqc_config.yml
  - assets/email_template.html
  - assets/sendmail_template.txt
  - assets/email_template.txt
  - CODE_OF_CONDUCT.md
  - assets/nf-core-demo_workflow_logo_light.png
  - docs/images/nf-core-demo_workflow_logo_light.png
  - docs/images/nf-core-demo_workflow_logo_dark.png
  - .github/ISSUE_TEMPLATE/config.yml
  - .github/workflows/awstest.yml
  - .github/workflows/awsfulltest.yml
  files_unchanged:
  - .github/CONTRIBUTING.md
  - assets/sendmail_template.txt
  - .prettierignore
  - .prettierignore
  - .prettierignore
  - .github/CONTRIBUTING.md
  - assets/sendmail_template.txt
  - .prettierignore
  - .prettierignore
  - .prettierignore
  - CODE_OF_CONDUCT.md
  - assets/nf-core-demo_workflow_logo_light.png
  - docs/images/nf-core-demo_workflow_logo_light.png
  - docs/images/nf-core-demo_workflow_logo_dark.png
  - .github/ISSUE_TEMPLATE/bug_report.yml
  files_warn:
  - ro-crate-metadata.json
  - ro-crate-metadata.json
  included_configs: false
  multiqc_config: false
  nextflow_config:
  - process.cpus
  - process.memory
  - process.time
  - custom_config
  - params.custom_config_version
  - params.custom_config_base
  - manifest.name
  - manifest.homePage
  - validation.help.beforeText
  - validation.help.afterText
  - validation.summary.beforeText
  - validation.summary.afterText
  readme:
  - nextflow_badge
nf_core_version: 3.0.3.dev0
repository_type: pipeline
template:
  author: '@kbestak'
  description: Demo workflow in Nextflow using nf-core modules
  force: true
  is_nfcore: false
  name: demo_workflow
  org: kbestak
  outdir: /workspace/demo_pipeline
  skip_features:
  - igenomes
  - github_badges
  - nf_core_configs
  - multiqc
  - fastqc
  - email
  - adaptivecard
  - slackreport
  - seqera_platform
  - rocrate
  version: 1.0.0dev
update: null
